apiVersion: v1
kind: ServiceAccount
metadata:
        name: dino
        namespace: kubeflow-user-example-com
        annotations:
                eks.amazonaws.com/role-arn: "I don't know"
                serving.kserve.io/s3-endpoint: "I don't know"
                serving.kserve.io/s3-usehttps: "I don't know"
                serving.kserve.io/s3-region: "I don't know"
                serving.kserve.io/s3-useanoncredential: "I don't know"

---

apiVersion: v1
kind: Secret
metadata:
        name: dino-s3creds
        namespace: kubeflow-user-example-com
        annotations:
                serving.kserve.io/s3-endpoint: "I don't know"
                serving.kserve.io/s3-usehttps: "I don't know"
                serving.kserve.io/s3-region: "I don't know"
                serving.kserve.io/s3-useanoncredential: "I don't know"
type: Opaque
stringData:
        AWS_ACCESS_KEY_ID: "I don't know"
        AWS_SECRET_ACCESS_KEY: "I don't know"

---

apiVersion: v1
kind: ServiceAccount
metadata:
          name: dino
          namespace: kubeflow-user-example-com
secrets:
        - name: dino-s3creds


